{
 "title": "Golang服务监控",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "服务",
    "query": "label_values(grpc_server_started_total{grpc_method=\"Check\"}, job)"
   },
   {
    "name": "instance",
    "label": "实例",
    "query": "label_values(grpc_server_started_total{grpc_method=\"Check\",job=~\"$service\"}, instance)"
   },
   {
    "name": "method",
    "label": "接口",
    "query": "label_values(grpc_server_started_total{job=~\"$service\", instance=~\"$instance\"}, grpc_method)"
   },
   { "name": "line", "label": "请求基线", "query": "0.99,0.95" }
  ]
 },
 "panels": [
  { "title": "监控概览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "接口异常率TopN",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(10, (100* sum(grpc_server_handled_total{grpc_method=~\"$method\", instance=~\"$instance\", job=~\"$service\", grpc_type=\"unary\",grpc_code!=\"OK\"}) by (grpc_method) /sum(grpc_server_handled_total{grpc_method=~\"$method\", instance=~\"$instance\", job=~\"$service\", grpc_type=\"unary\"}) by (grpc_method) ))"
    }
   ]
  },
  {
   "title": "服务异常率TopN",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(10, (100* sum(grpc_server_handled_total{grpc_method=~\"$method\", instance=~\"$instance\", job=~\"$service\", grpc_type=\"unary\",grpc_code!=\"OK\"}) by (job) /sum(grpc_server_handled_total{grpc_method=~\"$method\", instance=~\"$instance\", job=~\"$service\", grpc_type=\"unary\"}) by (job) ))"
    }
   ]
  },
  {
   "title": "实例异常率TopN",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(5, (100* sum(grpc_server_handled_total{grpc_method=~\"$method\", instance=~\"$instance\", job=~\"$service\", grpc_type=\"unary\",grpc_code!=\"OK\"}) by (instance) /sum(grpc_server_handled_total{grpc_method=~\"$method\", instance=~\"$instance\", job=~\"$service\", grpc_type=\"unary\"}) by (instance) ))"
    }
   ]
  },
  { "title": "各服务详细监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "请求总数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(grpc_server_handled_total{grpc_method=~\"$method\", instance=~\"$instance\", job=~\"$service\", grpc_type=\"unary\"})",
     "legendFormat": "请求总数{{instance}}"
    }
   ]
  },
  {
   "title": "错误请求总数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(grpc_server_handled_total{grpc_method=~\"$method\", instance=~\"$instance\", job=~\"$service\", grpc_type=\"unary\",grpc_code!=\"OK\"})",
     "legendFormat": "错误请求{{instance}}"
    }
   ]
  },
  {
   "title": "成功请求数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(grpc_server_handled_total{grpc_method=~\"$method\", instance=~\"$instance\", job=~\"$service\", grpc_type=\"unary\",grpc_code=\"OK\"}) ",
     "legendFormat": "成功请求总数{{instance}}"
    }
   ]
  },
  {
   "title": "成功率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(grpc_server_handled_total{grpc_method=~\"$method\", instance=~\"$instance\", job=~\"$service\", grpc_type=\"unary\",grpc_code=\"OK\"}) /sum(grpc_server_handled_total{grpc_method=~\"$method\", instance=~\"$instance\", job=~\"$service\", grpc_type=\"unary\"})) * 100.0",
     "legendFormat": "OK率{{instance}}"
    },
    {
     "expr": "(sum(grpc_server_handled_total{grpc_method=~\"$method\", instance=~\"$instance\", job=~\"$service\", grpc_type=\"unary\",grpc_code=\"Unknown\"}) /sum(grpc_server_handled_total{grpc_method=~\"$method\", instance=~\"$instance\", job=~\"$service\", grpc_type=\"unary\"})) * 100.0",
     "legendFormat": "Unknown率{{instance}}"
    },
    {
     "expr": "(sum(grpc_server_handled_total{grpc_method=~\"$method\", instance=~\"$instance\", job=~\"$service\", grpc_type=\"unary\",grpc_code=\"InvalidArgument\"}) /sum(grpc_server_handled_total{grpc_method=~\"$method\", instance=~\"$instance\", job=~\"$service\", grpc_type=\"unary\"})) * 100.0",
     "legendFormat": "InvalidArgument率{{instance}}"
    },
    {
     "expr": "(sum(grpc_server_handled_total{grpc_method=~\"$method\", instance=~\"$instance\", job=~\"$service\", grpc_type=\"unary\",grpc_code!=\"OK\"}) /sum(grpc_server_handled_total{grpc_method=~\"$method\", instance=~\"$instance\", job=~\"$service\", grpc_type=\"unary\"})) * 100.0",
     "legendFormat": "NotOK率{{instance}}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "每秒请求数" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{grpc_method=~\"$method\", instance=~\"$instance\", job=~\"$service\"}[1m])) by (instance, grpc_method)"
    }
   ]
  },
  {
   "title": "大于250ms的百分比",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "慢请求百分比（%）" }
   ],
   "targets": [
    {
     "expr": "100.0 - (\nsum(rate(grpc_server_handling_seconds_bucket{grpc_method=~\"$method\", instance=~\"$instance\", job=~\"$service\",grpc_type=\"unary\",le=\"0.25\"}[5m])) by (instance)\n / \nsum(rate(grpc_server_handling_seconds_count{grpc_method=~\"$method\", instance=~\"$instance\", job=~\"$service\",grpc_type=\"unary\"}[5m])) by (instance)\n) * 100.0"
    }
   ]
  },
  {
   "title": "请求95线（ms）",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \n  sum(rate(grpc_server_handling_seconds_bucket{grpc_method=~\"$method\", instance=~\"$instance\", job=~\"$service\",grpc_type=\"unary\"}[5m])) by (instance,le)\n) * 1000",
     "legendFormat": "99线---{{instance}}"
    }
   ]
  },
  {
   "title": "错误率百分比",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_method=~\"$method\", instance=~\"$instance\", job=~\"$service\",grpc_type=\"unary\",grpc_code!=\"OK\"}[1m])) by (instance,grpc_method)\n / \nsum(rate(grpc_server_started_total{grpc_method=~\"$method\", instance=~\"$instance\", job=~\"$service\",grpc_type=\"unary\"}[1m])) by (instance, grpc_method)\n * 100.0"
    }
   ]
  },
  {
   "title": "错误率(%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_method=~\"$method\", instance=~\"$instance\", job=~\"$service\", grpc_type=\"unary\",grpc_code!=\"OK\"}[1m]) > 0) by (grpc_code, grpc_method) * 100"
    }
   ]
  }
 ]
}