{
 "title": "Golang服务监控",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "服务",
    "query": {
     "query": "label_values(grpc_server_started_total{grpc_method=\"Check\"}, job)"
    }
   },
   {
    "name": "instance",
    "label": "实例",
    "query": {
     "query": "label_values(grpc_server_started_total{grpc_method=\"Check\",job=~\"$service\"}, instance)"
    }
   },
   {
    "name": "method",
    "label": "接口",
    "query": {
     "query": "label_values(grpc_server_started_total{job=~\"$service\", instance=~\"$instance\"}, grpc_method)"
    }
   },
   { "name": "line", "label": "请求基线", "query": "0.99,0.95" }
  ]
 },
 "panels": [
  {
   "title": "监控概览",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "接口异常率TopN",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "topk(10, (100* sum(grpc_server_handled_total{grpc_type=\"unary\",grpc_code!=\"OK\"}) by (grpc_method) /sum(grpc_server_handled_total{grpc_type=\"unary\"}) by (grpc_method) ))"
      }
     ]
    },
    {
     "title": "服务异常率TopN",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "topk(10, (100* sum(grpc_server_handled_total{ grpc_type=\"unary\",grpc_code!=\"OK\"}) by (job) /sum(grpc_server_handled_total{ grpc_type=\"unary\"}) by (job) ))"
      }
     ]
    },
    {
     "title": "实例异常率TopN",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "topk(5, (100* sum(grpc_server_handled_total{ grpc_type=\"unary\",grpc_code!=\"OK\"}) by (instance) /sum(grpc_server_handled_total{ grpc_type=\"unary\"}) by (instance) ))"
      }
     ]
    }
   ]
  },
  { "title": "各服务详细监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "请求数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_method=~\"$method\", instance=~\"$instance\", job=~\"$service\", grpc_type=\"unary\"}[5m]))",
     "legendFormat": "今日-请求总数{{instance}}"
    },
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_method=~\"$method\", instance=~\"$instance\", job=~\"$service\", grpc_type=\"unary\"}[5m] offset 1d))",
     "legendFormat": "昨天-请求总数{{instance}}"
    }
   ]
  },
  {
   "title": "错误请求数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_method=~\"$method\", instance=~\"$instance\", job=~\"$service\", grpc_type=\"unary\",grpc_code!=\"OK\"}[5m]))",
     "legendFormat": "今日-错误请求{{instance}}"
    },
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_method=~\"$method\", instance=~\"$instance\", job=~\"$service\", grpc_type=\"unary\",grpc_code!=\"OK\"}[5m] offset 1d))",
     "legendFormat": "昨日-错误请求{{instance}}"
    }
   ]
  },
  {
   "title": "成功请求数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_method=~\"$method\", instance=~\"$instance\", job=~\"$service\", grpc_type=\"unary\",grpc_code=\"OK\"}[5m])) ",
     "legendFormat": "今日-成功请求总数{{instance}}"
    },
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_method=~\"$method\", instance=~\"$instance\", job=~\"$service\", grpc_type=\"unary\",grpc_code=\"OK\"}[5m] offset 1d)) ",
     "legendFormat": "昨日-成功请求总数{{instance}}"
    }
   ]
  },
  {
   "title": "成功率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(grpc_server_handled_total{grpc_method=~\"$method\", instance=~\"$instance\", job=~\"$service\", grpc_type=\"unary\",grpc_code=\"OK\"}[5m])) /sum(rate(grpc_server_handled_total{grpc_method=~\"$method\", instance=~\"$instance\", job=~\"$service\", grpc_type=\"unary\"}[5m]))) * 100.0",
     "legendFormat": "OK率{{instance}}"
    },
    {
     "expr": "(sum(rate(grpc_server_handled_total{grpc_method=~\"$method\", instance=~\"$instance\", job=~\"$service\", grpc_type=\"unary\",grpc_code=\"Unknown\"}[5m])) /sum(rate(grpc_server_handled_total{grpc_method=~\"$method\", instance=~\"$instance\", job=~\"$service\", grpc_type=\"unary\"}[5m]))) * 100.0",
     "legendFormat": "Unknown率{{instance}}"
    },
    {
     "expr": "(sum(rate(grpc_server_handled_total{grpc_method=~\"$method\", instance=~\"$instance\", job=~\"$service\", grpc_type=\"unary\",grpc_code=\"InvalidArgument\"}[5m])) /sum(rate(grpc_server_handled_total{grpc_method=~\"$method\", instance=~\"$instance\", job=~\"$service\", grpc_type=\"unary\"}[5m]))) * 100.0",
     "legendFormat": "InvalidArgument率{{instance}}"
    },
    {
     "expr": "(sum(rate(grpc_server_handled_total{grpc_method=~\"$method\", instance=~\"$instance\", job=~\"$service\", grpc_type=\"unary\",grpc_code!=\"OK\"}[5m])) /sum(rate(grpc_server_handled_total{grpc_method=~\"$method\", instance=~\"$instance\", job=~\"$service\", grpc_type=\"unary\"}[5m]))) * 100.0",
     "legendFormat": "NotOK率{{instance}}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "每秒请求数" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{grpc_method=~\"$method\", instance=~\"$instance\", job=~\"$service\"}[1m])) by (instance, grpc_method) > 0.1"
    }
   ]
  },
  {
   "title": "错误率百分比",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_method=~\"$method\", instance=~\"$instance\", job=~\"$service\",grpc_type=\"unary\",grpc_code!=\"OK\"}[1m])) by (instance,grpc_method)\n / \nsum(rate(grpc_server_started_total{grpc_method=~\"$method\", instance=~\"$instance\", job=~\"$service\",grpc_type=\"unary\"}[1m])) by (instance, grpc_method)\n * 100.0"
    }
   ]
  },
  {
   "title": "错误率(%)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 4, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_method=~\"$method\", instance=~\"$instance\", job=~\"$service\", grpc_type=\"unary\",grpc_code!=\"OK\"}[1m]) > 0) by (grpc_code, grpc_method) * 100"
    }
   ]
  },
  {
   "title": "大于500ms的百分比",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 10, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "慢请求百分比（%）" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handling_seconds_bucket{grpc_method=~\"$method\", instance=~\"$instance\", job=~\"$service\",grpc_type=\"unary\",le=\"0.5\"}[5m])) by (instance) * 100 / sum(rate(grpc_server_handling_seconds_count{grpc_method=~\"$method\", instance=~\"$instance\", job=~\"$service\",grpc_type=\"unary\"}[5m])) by (instance) "
    }
   ]
  },
  {
   "title": "请求95线（ms）",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  sum(rate(grpc_server_handling_seconds_bucket{grpc_method=~\"$method\", instance=~\"$instance\", job=~\"$service\",grpc_type=\"unary\"}[5m])) by (le)\n)",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, \n  sum(rate(grpc_server_handling_seconds_bucket{grpc_method=~\"$method\", instance=~\"$instance\", job=~\"$service\",grpc_type=\"unary\"}[5m])) by (le)\n)",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, \n  sum(rate(grpc_server_handling_seconds_bucket{grpc_method=~\"$method\", instance=~\"$instance\", job=~\"$service\",grpc_type=\"unary\"}[5m])) by (le)\n)",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "请求95线（ms）",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum (rate(grpc_server_handling_seconds_bucket{instance=~\"$instance\", job=~\"$service\", grpc_method=~\"$method\"}[5m])) by (le, grpc_method))"
    }
   ]
  }
 ]
}