{
 "title": "网关监控",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "实例",
    "query": {
     "query": "label_values(ficool_gin_request_total{job=\"goApiService\"}, instance)"
    }
   },
   {
    "name": "path",
    "label": "接口",
    "query": {
     "query": "label_values(ficool_gin_request_total{job=\"goApiService\", instance=~\"$instance\"}, path)"
    }
   },
   {
    "name": "version",
    "label": "客户端版本",
    "query": {
     "query": "label_values(ficool_gin_result_request_total{job=\"goApiService\", path!=\"/app/api/v2/client/app-update\"}, version)"
    }
   },
   {
    "name": "app_type",
    "label": "客户端类型",
    "query": {
     "query": "label_values(ficool_gin_result_request_total{instance=~\"$instance\"}, app_type)"
    }
   }
  ]
 },
 "panels": [
  { "title": "监控大盘", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "实时QPS",
   "type": "gauge",
   "description": "Application request rate every 5 minutes.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(ficool_gin_request_total{instance=~\"$instance\"}[5m]))"
    }
   ]
  },
  {
   "title": "QPS日期对比",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ficool_gin_result_request_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "今日-QPS"
    },
    {
     "expr": "sum(rate(ficool_gin_result_request_total{instance=~\"$instance\"}[5m] offset 1d))",
     "legendFormat": "昨日-QPS"
    },
    {
     "expr": "sum(rate(ficool_gin_result_request_total{instance=~\"$instance\"}[5m] offset 7d))",
     "legendFormat": "7日-QPS"
    }
   ]
  },
  {
   "title": "QPS实例对比",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ficool_gin_result_request_total{path=~\"$path\",app_type=~\"$app_type\"}[5m])) by (instance)",
     "legendFormat": "实例-{{instance}}"
    }
   ]
  },
  {
   "title": "QPS客户端类型对比",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ficool_gin_result_request_total{instance=~\"$instance\", path=~\"$path\"}[5m])) by (app_type) > 1",
     "legendFormat": "{{app_type}}"
    }
   ]
  },
  {
   "title": "QPS接口对比",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ficool_gin_result_request_total{app_type=~\"$app_type\"}[5m])) by (path) > 1",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "版本分布",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(version) (ficool_gin_result_request_total{instance=~\"$instance\", path=~\"$path\",version=~\"[0-9].[0-9].[0-9].[0-9]\",app_type=~\"$app_type\"})",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "业务码",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(result) (ficool_gin_result_request_total{instance=~\"$instance\", path=~\"$path\", version=~\"$version\",app_type=~\"$app_type\"})",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "请求错误率（总）",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by(path) (ficool_gin_result_request_total{result!=\"0\",instance=~\"$instance\"})*100/sum by(path) (ficool_gin_result_request_total{instance=~\"$instance\"}))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "未知请求错误率",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by(path) (ficool_gin_result_request_total{result=\"999999\",instance=~\"$instance\"})*100/sum by(path) (ficool_gin_result_request_total{instance=~\"$instance\"}))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "请求错误数（总）",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by(path) (ficool_gin_result_request_total{result!=\"0\", instance=~\"$instance\"}))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "未知请求错误数",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by(path) (ficool_gin_result_request_total{result=\"999999\", instance=~\"$instance\"}))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  { "title": "监控明细", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "请求错误率",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by(path) (ficool_gin_result_request_total{result!=\"0\",instance=~\"$instance\", path=~\"$path\", version=~\"$version\",app_type=~\"$app_type\"})*100/sum by(path) (ficool_gin_result_request_total{instance=~\"$instance\", path=~\"$path\", version=~\"$version\",app_type=~\"$app_type\"}))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "请求错误总数",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by(path) (ficool_gin_result_request_total{instance=~\"$instance\", path=~\"$path\", version=~\"$version\",app_type=~\"$app_type\", result!=\"0\"}))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "实时QPS",
   "type": "gauge",
   "description": "Application request rate every 5 minutes.",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(ficool_gin_result_request_total{instance=~\"$instance\",path=~\"$path\",version=~\"$version\",app_type=~\"$app_type\"}[5m]))"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 2, "x": 14, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(code) (ficool_gin_result_request_total{instance=~\"$instance\",path=~\"$path\",version=~\"$version\",app_type=~\"$app_type\"})",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Slow Request(default 5s)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by(path) (ficool_gin_slow_request_total{instance=~\"$instance\", path=~\"$path\"}) > 0)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Method",
   "type": "piechart",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(method) (ficool_gin_result_request_total{instance=~\"$instance\", path=~\"$path\", version=~\"$version\"})",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Traffic In-Out",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ficool_gin_request_body_total{instance=~\"$instance\", path=~\"$path\"}[5m]))",
     "legendFormat": "in"
    },
    {
     "expr": "sum(rate(ficool_gin_response_body_total{instance=~\"$instance\", path=~\"$path\"}[5m]))",
     "legendFormat": "out"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum (rate(ficool_gin_request_duration_bucket{instance=~\"$instance\", path=~\"$path\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum (rate(ficool_gin_request_duration_bucket{instance=~\"$instance\", path=~\"$path\"}[5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.5, sum (rate(ficool_gin_request_duration_bucket{instance=~\"$instance\", path=~\"$path\"}[5m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "接口请求耗时",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum (rate(ficool_gin_request_duration_bucket{instance=~\"$instance\", path=~\"$path\"}[5m])) by (le, path))"
    }
   ]
  }
 ]
}