{
 "title": "聚合搜索服务监控",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": "label_values(application)" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(search_request_total{application=\"$application\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "概览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(search_request_total{application=\"$application\", instance=\"$instance\",type=\"total\"}[1m])",
     "legendFormat": "聚合搜索"
    },
    {
     "expr": "rate(search_request_total{application=\"$application\", instance=\"$instance\",type=\"initiate\"}[1m])",
     "legendFormat": "三方搜索"
    }
   ]
  },
  {
   "title": "聚合搜索接口耗时(ms)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "search_timeConsuming{ application=\"$application\", instance=\"$instance\",type=\"0\"}",
     "legendFormat": "ToTal"
    }
   ]
  },
  {
   "title": "搜索累计请求数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "search_request_total{type=\"total\",application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "聚合搜索"
    },
    {
     "expr": "search_request_total{type=\"initiate\",application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "三方搜索"
    }
   ]
  },
  { "title": "各搜索来源请求耗时详情", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "自有内容库搜索耗时(ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "search_timeConsuming{ application=\"$application\", instance=\"$instance\",type=\"4\"}",
     "legendFormat": "CONTENT"
    }
   ]
  },
  {
   "title": "PDF_DRIVE搜索耗时(ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "search_timeConsuming{ application=\"$application\", instance=\"$instance\",type=\"1\"}",
     "legendFormat": "PDF_DRIVE"
    }
   ]
  },
  {
   "title": "B_OK搜索耗时(ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "search_timeConsuming{ application=\"$application\", instance=\"$instance\",type=\"2\"}",
     "legendFormat": "B_OK"
    }
   ]
  },
  {
   "title": "LIB_GEN搜索耗时(ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "search_timeConsuming{ application=\"$application\", instance=\"$instance\",type=\"3\"}",
     "legendFormat": "LIB_GEN"
    }
   ]
  },
  { "title": "各搜索来源异常详情", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "PDF_DRIVE搜索异常数（5分钟）",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(extSearch_exception_total{application=\"$application\", instance=\"$instance\",type=\"1\"}[5m]))",
     "legendFormat": "PDF_DRIVE"
    }
   ]
  },
  {
   "title": "B_OK搜索异常数（5分钟）",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(extSearch_exception_total{application=\"$application\", instance=\"$instance\",type=\"2\"}[5m]))",
     "legendFormat": "B_OK"
    }
   ]
  },
  {
   "title": "LIB_GEN搜索异常数（5分钟）",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(extSearch_exception_total{application=\"$application\", instance=\"$instance\",type=\"3\"}[5m]))",
     "legendFormat": "LIB_GEN"
    }
   ]
  },
  {
   "title": "自有内容库搜索异常数（5分钟）",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(extSearch_exception_total{application=\"$application\", instance=\"$instance\",type=\"4\"}[5m]))",
     "legendFormat": "CONTENT"
    }
   ]
  }
 ]
}