// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: common/pagination.proto

package common

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on PaginationReq with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *PaginationReq) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetPage() <= 0 {
		return PaginationReqValidationError{
			field:  "Page",
			reason: "value must be greater than 0",
		}
	}

	if val := m.GetPageSize(); val <= 0 || val > 5000 {
		return PaginationReqValidationError{
			field:  "PageSize",
			reason: "value must be inside range (0, 5000]",
		}
	}

	// no validation rules for Sort

	return nil
}

// PaginationReqValidationError is the validation error returned by
// PaginationReq.Validate if the designated constraints aren't met.
type PaginationReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PaginationReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PaginationReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PaginationReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PaginationReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PaginationReqValidationError) ErrorName() string { return "PaginationReqValidationError" }

// Error satisfies the builtin error interface
func (e PaginationReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPaginationReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PaginationReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PaginationReqValidationError{}

// Validate checks the field values on TimeRange with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *TimeRange) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetStart() <= 0 {
		return TimeRangeValidationError{
			field:  "Start",
			reason: "value must be greater than 0",
		}
	}

	if m.GetEnd() <= 0 {
		return TimeRangeValidationError{
			field:  "End",
			reason: "value must be greater than 0",
		}
	}

	return nil
}

// TimeRangeValidationError is the validation error returned by
// TimeRange.Validate if the designated constraints aren't met.
type TimeRangeValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TimeRangeValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TimeRangeValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TimeRangeValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TimeRangeValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TimeRangeValidationError) ErrorName() string { return "TimeRangeValidationError" }

// Error satisfies the builtin error interface
func (e TimeRangeValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTimeRange.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TimeRangeValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TimeRangeValidationError{}
