// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: common.proto

//指定包名

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AppIdEnum int32

const (
	AppIdEnum_APP_ID_DEFAULT AppIdEnum = 0
	AppIdEnum_LIGHTHOUSE     AppIdEnum = 100
)

var AppIdEnum_name = map[int32]string{
	0:   "APP_ID_DEFAULT",
	100: "LIGHTHOUSE",
}

var AppIdEnum_value = map[string]int32{
	"APP_ID_DEFAULT": 0,
	"LIGHTHOUSE":     100,
}

func (x AppIdEnum) String() string {
	return proto.EnumName(AppIdEnum_name, int32(x))
}

func (AppIdEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

type AreaIdEnum int32

const (
	AreaIdEnum_AREA_ID_DEFAULT AreaIdEnum = 0
	AreaIdEnum_ANDROID         AreaIdEnum = 30
	AreaIdEnum_IOS             AreaIdEnum = 40
	AreaIdEnum_WEB             AreaIdEnum = 99
	AreaIdEnum_H5              AreaIdEnum = 98
)

var AreaIdEnum_name = map[int32]string{
	0:  "AREA_ID_DEFAULT",
	30: "ANDROID",
	40: "IOS",
	99: "WEB",
	98: "H5",
}

var AreaIdEnum_value = map[string]int32{
	"AREA_ID_DEFAULT": 0,
	"ANDROID":         30,
	"IOS":             40,
	"WEB":             99,
	"H5":              98,
}

func (x AreaIdEnum) String() string {
	return proto.EnumName(AreaIdEnum_name, int32(x))
}

func (AreaIdEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

type LanguageEnum int32

const (
	LanguageEnum_ZH LanguageEnum = 0
	LanguageEnum_EN LanguageEnum = 1
	LanguageEnum_ES LanguageEnum = 2
	LanguageEnum_IN LanguageEnum = 3
	LanguageEnum_TL LanguageEnum = 4
	LanguageEnum_MS LanguageEnum = 5
	LanguageEnum_KO LanguageEnum = 6
)

var LanguageEnum_name = map[int32]string{
	0: "ZH",
	1: "EN",
	2: "ES",
	3: "IN",
	4: "TL",
	5: "MS",
	6: "KO",
}

var LanguageEnum_value = map[string]int32{
	"ZH": 0,
	"EN": 1,
	"ES": 2,
	"IN": 3,
	"TL": 4,
	"MS": 5,
	"KO": 6,
}

func (x LanguageEnum) String() string {
	return proto.EnumName(LanguageEnum_name, int32(x))
}

func (LanguageEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2}
}

type InParam struct {
	AppId                int32    `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AreaId               int32    `protobuf:"varint,2,opt,name=area_id,json=areaId,proto3" json:"area_id,omitempty"`
	Version              int32    `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	UserId               int64    `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId             string   `protobuf:"bytes,5,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	ClientIp             string   `protobuf:"bytes,6,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	Channel              string   `protobuf:"bytes,7,opt,name=channel,proto3" json:"channel,omitempty"`
	Source               string   `protobuf:"bytes,8,opt,name=source,proto3" json:"source,omitempty"`
	UserIp               string   `protobuf:"bytes,9,opt,name=user_ip,json=userIp,proto3" json:"user_ip,omitempty"`
	Language             string   `protobuf:"bytes,10,opt,name=language,proto3" json:"language,omitempty"`
	Country              string   `protobuf:"bytes,11,opt,name=country,proto3" json:"country,omitempty"`
	AuthorId             int64    `protobuf:"varint,12,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InParam) Reset()         { *m = InParam{} }
func (m *InParam) String() string { return proto.CompactTextString(m) }
func (*InParam) ProtoMessage()    {}
func (*InParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}
func (m *InParam) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *InParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_InParam.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *InParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InParam.Merge(m, src)
}
func (m *InParam) XXX_Size() int {
	return m.Size()
}
func (m *InParam) XXX_DiscardUnknown() {
	xxx_messageInfo_InParam.DiscardUnknown(m)
}

var xxx_messageInfo_InParam proto.InternalMessageInfo

func (m *InParam) GetAppId() int32 {
	if m != nil {
		return m.AppId
	}
	return 0
}

func (m *InParam) GetAreaId() int32 {
	if m != nil {
		return m.AreaId
	}
	return 0
}

func (m *InParam) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *InParam) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *InParam) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *InParam) GetClientIp() string {
	if m != nil {
		return m.ClientIp
	}
	return ""
}

func (m *InParam) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *InParam) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *InParam) GetUserIp() string {
	if m != nil {
		return m.UserIp
	}
	return ""
}

func (m *InParam) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *InParam) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *InParam) GetAuthorId() int64 {
	if m != nil {
		return m.AuthorId
	}
	return 0
}

type OutParam struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	SubCode              int32    `protobuf:"varint,2,opt,name=sub_code,json=subCode,proto3" json:"sub_code,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Reason               string   `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutParam) Reset()         { *m = OutParam{} }
func (m *OutParam) String() string { return proto.CompactTextString(m) }
func (*OutParam) ProtoMessage()    {}
func (*OutParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}
func (m *OutParam) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OutParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OutParam.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OutParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutParam.Merge(m, src)
}
func (m *OutParam) XXX_Size() int {
	return m.Size()
}
func (m *OutParam) XXX_DiscardUnknown() {
	xxx_messageInfo_OutParam.DiscardUnknown(m)
}

var xxx_messageInfo_OutParam proto.InternalMessageInfo

func (m *OutParam) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *OutParam) GetSubCode() int32 {
	if m != nil {
		return m.SubCode
	}
	return 0
}

func (m *OutParam) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *OutParam) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func init() {
	proto.RegisterEnum("common.v1.AppIdEnum", AppIdEnum_name, AppIdEnum_value)
	proto.RegisterEnum("common.v1.AreaIdEnum", AreaIdEnum_name, AreaIdEnum_value)
	proto.RegisterEnum("common.v1.LanguageEnum", LanguageEnum_name, LanguageEnum_value)
	proto.RegisterType((*InParam)(nil), "common.v1.InParam")
	proto.RegisterType((*OutParam)(nil), "common.v1.OutParam")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 492 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x52, 0xcb, 0x8e, 0xd3, 0x30,
	0x14, 0x6d, 0xfa, 0xc8, 0xe3, 0x4e, 0x35, 0x58, 0x46, 0x40, 0x00, 0xa9, 0xaa, 0x66, 0x55, 0x75,
	0x31, 0x15, 0x42, 0xac, 0x60, 0x93, 0xa1, 0x19, 0x6a, 0x51, 0xda, 0x2a, 0xed, 0x08, 0x69, 0x36,
	0x95, 0x93, 0x58, 0x6d, 0x44, 0x63, 0x47, 0x49, 0x5c, 0x09, 0xbe, 0x84, 0x0f, 0x62, 0xc1, 0x92,
	0x4f, 0x40, 0xe5, 0x47, 0x90, 0xed, 0x14, 0x34, 0xd9, 0x1c, 0x9f, 0x73, 0x74, 0x73, 0xee, 0xbd,
	0x36, 0xf4, 0x13, 0x91, 0xe7, 0x82, 0x5f, 0x17, 0xa5, 0xa8, 0x05, 0xf6, 0x1a, 0x76, 0x7c, 0x75,
	0xf5, 0xa3, 0x0d, 0x0e, 0xe1, 0x2b, 0x5a, 0xd2, 0x1c, 0x3f, 0x01, 0x9b, 0x16, 0xc5, 0x36, 0x4b,
	0x7d, 0x6b, 0x68, 0x8d, 0x7a, 0x51, 0x8f, 0x16, 0x05, 0x49, 0xf1, 0x33, 0x70, 0x68, 0xc9, 0xa8,
	0xd2, 0xdb, 0x5a, 0xb7, 0x15, 0x25, 0x29, 0xf6, 0xc1, 0x39, 0xb2, 0xb2, 0xca, 0x04, 0xf7, 0x3b,
	0xda, 0x38, 0x53, 0x55, 0x22, 0x2b, 0x56, 0xaa, 0x92, 0xee, 0xd0, 0x1a, 0x75, 0x22, 0x5b, 0x51,
	0x92, 0xe2, 0x97, 0xe0, 0xa5, 0xec, 0x98, 0x25, 0x4c, 0x59, 0xbd, 0xa1, 0x35, 0xf2, 0x22, 0xd7,
	0x08, 0xc6, 0x4c, 0x0e, 0x19, 0xe3, 0xf5, 0x36, 0x2b, 0x7c, 0xdb, 0x98, 0x46, 0x20, 0x85, 0x0a,
	0x4b, 0xf6, 0x94, 0x73, 0x76, 0xf0, 0x1d, 0x6d, 0x9d, 0x29, 0x7e, 0x0a, 0x76, 0x25, 0x64, 0x99,
	0x30, 0xdf, 0xd5, 0x46, 0xc3, 0xfe, 0x37, 0x51, 0xf8, 0x9e, 0x31, 0x74, 0x13, 0x05, 0x7e, 0x01,
	0xee, 0x81, 0xf2, 0x9d, 0xa4, 0x3b, 0xe6, 0x83, 0x89, 0x39, 0x73, 0x1d, 0x23, 0x24, 0xaf, 0xcb,
	0xaf, 0xfe, 0x45, 0x13, 0x63, 0xa8, 0xea, 0x8e, 0xca, 0x7a, 0x2f, 0xf4, 0x54, 0x7d, 0x3d, 0x95,
	0x6b, 0x04, 0x92, 0x5e, 0x7d, 0x01, 0x77, 0x29, 0x6b, 0xb3, 0x46, 0x0c, 0xdd, 0x44, 0xa4, 0xac,
	0x59, 0xa2, 0x3e, 0xe3, 0xe7, 0xe0, 0x56, 0x32, 0xde, 0x6a, 0xdd, 0x2c, 0xd1, 0xa9, 0x64, 0xfc,
	0x5e, 0x59, 0x3e, 0x38, 0x39, 0xab, 0x2a, 0xd5, 0x4c, 0xc7, 0x24, 0x36, 0x54, 0x0d, 0x56, 0x32,
	0x5a, 0x09, 0xae, 0x97, 0xe8, 0x45, 0x0d, 0x1b, 0x4f, 0xc0, 0x0b, 0xd4, 0xcd, 0x84, 0x5c, 0xaa,
	0xb4, 0xcb, 0x60, 0xb5, 0xda, 0x92, 0xe9, 0x76, 0x1a, 0xde, 0x06, 0x77, 0xf3, 0x0d, 0x6a, 0xe1,
	0x4b, 0x80, 0x39, 0xf9, 0x30, 0xdb, 0xcc, 0x96, 0x77, 0xeb, 0x10, 0xa5, 0xe3, 0x19, 0x40, 0xa0,
	0xaf, 0x4c, 0x57, 0x3c, 0x86, 0x47, 0x41, 0x14, 0x06, 0x0f, 0x4b, 0x2e, 0xc0, 0x09, 0x16, 0xd3,
	0x68, 0x49, 0xa6, 0x68, 0x80, 0x1d, 0xe8, 0x90, 0xe5, 0x1a, 0x8d, 0xd4, 0xe1, 0x73, 0x78, 0x83,
	0x12, 0x6c, 0x43, 0x7b, 0xf6, 0x06, 0xc5, 0xe3, 0x5b, 0xe8, 0xcf, 0x9b, 0x55, 0xe9, 0x7f, 0xd9,
	0xd0, 0xbe, 0x9f, 0xa1, 0x96, 0xc2, 0x70, 0x81, 0x2c, 0x8d, 0x6b, 0xd4, 0x56, 0x48, 0x16, 0xa8,
	0xa3, 0x70, 0x33, 0x47, 0x5d, 0x85, 0x9f, 0xd6, 0xa8, 0xa7, 0xf0, 0xe3, 0x12, 0xd9, 0x37, 0xef,
	0x7e, 0x9e, 0x06, 0xd6, 0xaf, 0xd3, 0xc0, 0xfa, 0x7d, 0x1a, 0x58, 0xdf, 0xff, 0x0c, 0x5a, 0xf7,
	0xe3, 0x5d, 0x56, 0xef, 0x65, 0x7c, 0x9d, 0x88, 0x7c, 0x42, 0xbf, 0xa5, 0x31, 0xd5, 0xdf, 0x44,
	0xd6, 0xd9, 0x61, 0xa2, 0x5f, 0xed, 0xdb, 0x7f, 0x8f, 0x36, 0xb6, 0xb5, 0xf0, 0xfa, 0x6f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xdc, 0x72, 0xda, 0xc0, 0xd6, 0x02, 0x00, 0x00,
}

func (m *InParam) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *InParam) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *InParam) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.AuthorId != 0 {
		i = encodeVarintCommon(dAtA, i, uint64(m.AuthorId))
		i--
		dAtA[i] = 0x60
	}
	if len(m.Country) > 0 {
		i -= len(m.Country)
		copy(dAtA[i:], m.Country)
		i = encodeVarintCommon(dAtA, i, uint64(len(m.Country)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.Language) > 0 {
		i -= len(m.Language)
		copy(dAtA[i:], m.Language)
		i = encodeVarintCommon(dAtA, i, uint64(len(m.Language)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.UserIp) > 0 {
		i -= len(m.UserIp)
		copy(dAtA[i:], m.UserIp)
		i = encodeVarintCommon(dAtA, i, uint64(len(m.UserIp)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.Source) > 0 {
		i -= len(m.Source)
		copy(dAtA[i:], m.Source)
		i = encodeVarintCommon(dAtA, i, uint64(len(m.Source)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Channel) > 0 {
		i -= len(m.Channel)
		copy(dAtA[i:], m.Channel)
		i = encodeVarintCommon(dAtA, i, uint64(len(m.Channel)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.ClientIp) > 0 {
		i -= len(m.ClientIp)
		copy(dAtA[i:], m.ClientIp)
		i = encodeVarintCommon(dAtA, i, uint64(len(m.ClientIp)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.DeviceId) > 0 {
		i -= len(m.DeviceId)
		copy(dAtA[i:], m.DeviceId)
		i = encodeVarintCommon(dAtA, i, uint64(len(m.DeviceId)))
		i--
		dAtA[i] = 0x2a
	}
	if m.UserId != 0 {
		i = encodeVarintCommon(dAtA, i, uint64(m.UserId))
		i--
		dAtA[i] = 0x20
	}
	if m.Version != 0 {
		i = encodeVarintCommon(dAtA, i, uint64(m.Version))
		i--
		dAtA[i] = 0x18
	}
	if m.AreaId != 0 {
		i = encodeVarintCommon(dAtA, i, uint64(m.AreaId))
		i--
		dAtA[i] = 0x10
	}
	if m.AppId != 0 {
		i = encodeVarintCommon(dAtA, i, uint64(m.AppId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *OutParam) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OutParam) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OutParam) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Reason) > 0 {
		i -= len(m.Reason)
		copy(dAtA[i:], m.Reason)
		i = encodeVarintCommon(dAtA, i, uint64(len(m.Reason)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Message) > 0 {
		i -= len(m.Message)
		copy(dAtA[i:], m.Message)
		i = encodeVarintCommon(dAtA, i, uint64(len(m.Message)))
		i--
		dAtA[i] = 0x1a
	}
	if m.SubCode != 0 {
		i = encodeVarintCommon(dAtA, i, uint64(m.SubCode))
		i--
		dAtA[i] = 0x10
	}
	if m.Code != 0 {
		i = encodeVarintCommon(dAtA, i, uint64(m.Code))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintCommon(dAtA []byte, offset int, v uint64) int {
	offset -= sovCommon(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *InParam) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AppId != 0 {
		n += 1 + sovCommon(uint64(m.AppId))
	}
	if m.AreaId != 0 {
		n += 1 + sovCommon(uint64(m.AreaId))
	}
	if m.Version != 0 {
		n += 1 + sovCommon(uint64(m.Version))
	}
	if m.UserId != 0 {
		n += 1 + sovCommon(uint64(m.UserId))
	}
	l = len(m.DeviceId)
	if l > 0 {
		n += 1 + l + sovCommon(uint64(l))
	}
	l = len(m.ClientIp)
	if l > 0 {
		n += 1 + l + sovCommon(uint64(l))
	}
	l = len(m.Channel)
	if l > 0 {
		n += 1 + l + sovCommon(uint64(l))
	}
	l = len(m.Source)
	if l > 0 {
		n += 1 + l + sovCommon(uint64(l))
	}
	l = len(m.UserIp)
	if l > 0 {
		n += 1 + l + sovCommon(uint64(l))
	}
	l = len(m.Language)
	if l > 0 {
		n += 1 + l + sovCommon(uint64(l))
	}
	l = len(m.Country)
	if l > 0 {
		n += 1 + l + sovCommon(uint64(l))
	}
	if m.AuthorId != 0 {
		n += 1 + sovCommon(uint64(m.AuthorId))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *OutParam) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Code != 0 {
		n += 1 + sovCommon(uint64(m.Code))
	}
	if m.SubCode != 0 {
		n += 1 + sovCommon(uint64(m.SubCode))
	}
	l = len(m.Message)
	if l > 0 {
		n += 1 + l + sovCommon(uint64(l))
	}
	l = len(m.Reason)
	if l > 0 {
		n += 1 + l + sovCommon(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovCommon(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCommon(x uint64) (n int) {
	return sovCommon(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *InParam) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCommon
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: InParam: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: InParam: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AppId", wireType)
			}
			m.AppId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AppId |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AreaId", wireType)
			}
			m.AreaId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AreaId |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			m.Version = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Version |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserId", wireType)
			}
			m.UserId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UserId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeviceId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCommon
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCommon
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DeviceId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientIp", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCommon
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCommon
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClientIp = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Channel", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCommon
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCommon
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Channel = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Source", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCommon
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCommon
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Source = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserIp", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCommon
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCommon
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserIp = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Language", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCommon
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCommon
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Language = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Country", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCommon
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCommon
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Country = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuthorId", wireType)
			}
			m.AuthorId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AuthorId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipCommon(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCommon
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *OutParam) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCommon
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OutParam: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OutParam: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			m.Code = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Code |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubCode", wireType)
			}
			m.SubCode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SubCode |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Message", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCommon
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCommon
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Message = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reason", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCommon
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCommon
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reason = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCommon(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCommon
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCommon(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCommon
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCommon
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCommon
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCommon
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCommon
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCommon
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCommon        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCommon          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCommon = fmt.Errorf("proto: unexpected end of group")
)
