// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pagination.proto

//指定包名

package proto

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SortOrder int32

const (
	SortOrder_SortDefault SortOrder = 0
	SortOrder_SortDesc    SortOrder = 1
	SortOrder_SortAsc     SortOrder = 2
)

var SortOrder_name = map[int32]string{
	0: "SortDefault",
	1: "SortDesc",
	2: "SortAsc",
}

var SortOrder_value = map[string]int32{
	"SortDefault": 0,
	"SortDesc":    1,
	"SortAsc":     2,
}

func (x SortOrder) String() string {
	return proto.EnumName(SortOrder_name, int32(x))
}

func (SortOrder) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_567bfb3a87c868dd, []int{0}
}

type PaginationReq struct {
	Page                 int32                `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             int32                `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Sort                 map[string]SortOrder `protobuf:"bytes,3,rep,name=sort,proto3" json:"sort" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3,enum=proto.SortOrder"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PaginationReq) Reset()         { *m = PaginationReq{} }
func (m *PaginationReq) String() string { return proto.CompactTextString(m) }
func (*PaginationReq) ProtoMessage()    {}
func (*PaginationReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_567bfb3a87c868dd, []int{0}
}
func (m *PaginationReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PaginationReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PaginationReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PaginationReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaginationReq.Merge(m, src)
}
func (m *PaginationReq) XXX_Size() int {
	return m.Size()
}
func (m *PaginationReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PaginationReq.DiscardUnknown(m)
}

var xxx_messageInfo_PaginationReq proto.InternalMessageInfo

func (m *PaginationReq) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *PaginationReq) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *PaginationReq) GetSort() map[string]SortOrder {
	if m != nil {
		return m.Sort
	}
	return nil
}

func init() {
	proto.RegisterEnum("proto.SortOrder", SortOrder_name, SortOrder_value)
	proto.RegisterType((*PaginationReq)(nil), "proto.PaginationReq")
	proto.RegisterMapType((map[string]SortOrder)(nil), "proto.PaginationReq.SortEntry")
}

func init() { proto.RegisterFile("pagination.proto", fileDescriptor_567bfb3a87c868dd) }

var fileDescriptor_567bfb3a87c868dd = []byte{
	// 351 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x51, 0x31, 0x4f, 0xeb, 0x30,
	0x10, 0x8e, 0xd3, 0xe4, 0xb5, 0x75, 0xdf, 0x7b, 0x8d, 0x3c, 0x45, 0x41, 0x0a, 0x11, 0x43, 0xa9,
	0x90, 0x9a, 0x48, 0x65, 0xa0, 0x82, 0xa9, 0x11, 0x0c, 0x4c, 0xa0, 0x74, 0x63, 0x41, 0x6e, 0xea,
	0x06, 0x8b, 0x10, 0x07, 0xc7, 0xa9, 0x48, 0x7f, 0x09, 0x3f, 0xa9, 0x63, 0x67, 0x06, 0x84, 0xca,
	0xbf, 0xe8, 0x84, 0x62, 0xa3, 0xaa, 0x08, 0x2f, 0x77, 0xdf, 0x77, 0xf7, 0xdd, 0x77, 0x3a, 0x43,
	0x2b, 0xc7, 0x09, 0xcd, 0xb0, 0xa0, 0x2c, 0xf3, 0x73, 0xce, 0x04, 0x43, 0xa6, 0x0c, 0xce, 0x20,
	0xa1, 0xe2, 0xa1, 0x9c, 0xfa, 0x31, 0x7b, 0x0a, 0x12, 0x96, 0xb0, 0x40, 0xd2, 0xd3, 0x72, 0x2e,
	0x91, 0x04, 0x32, 0x53, 0x2a, 0x67, 0xbc, 0xd7, 0x4e, 0xb2, 0x05, 0xab, 0x72, 0xce, 0x5e, 0x2a,
	0x25, 0x8a, 0x07, 0x09, 0xc9, 0x06, 0x0b, 0x9c, 0xd2, 0x19, 0x16, 0x24, 0xf8, 0x95, 0xa8, 0x11,
	0x47, 0x6f, 0x00, 0xfe, 0xbb, 0xdd, 0x6d, 0x13, 0x91, 0x67, 0x74, 0x00, 0x8d, 0x1c, 0x27, 0xc4,
	0x06, 0x1e, 0xe8, 0x9b, 0x61, 0x73, 0x1b, 0x1a, 0x8e, 0xee, 0x69, 0x91, 0x24, 0xd1, 0x31, 0x6c,
	0xd7, 0xf1, 0xbe, 0xa0, 0x4b, 0x62, 0xeb, 0xb2, 0x03, 0x6e, 0xc3, 0xa6, 0x63, 0xda, 0xeb, 0xae,
	0xa7, 0x45, 0xad, 0xba, 0x38, 0xa1, 0x4b, 0x82, 0x46, 0xd0, 0x28, 0x18, 0x17, 0x76, 0xc3, 0x6b,
	0xf4, 0x3b, 0x43, 0x57, 0xb9, 0xf9, 0x3f, 0x9c, 0xfc, 0x09, 0xe3, 0xe2, 0x2a, 0x13, 0xbc, 0x0a,
	0x8d, 0xd5, 0xfb, 0xa1, 0x16, 0x49, 0x85, 0x73, 0x0d, 0xdb, 0xbb, 0x02, 0xb2, 0x60, 0xe3, 0x91,
	0x54, 0x72, 0x97, 0x76, 0x54, 0xa7, 0xa8, 0x07, 0xcd, 0x05, 0x4e, 0x4b, 0xe5, 0xfe, 0x7f, 0x68,
	0x7d, 0x4f, 0xae, 0x25, 0x37, 0x7c, 0x46, 0x78, 0xa4, 0xca, 0xe7, 0xfa, 0x08, 0x9c, 0x9c, 0xa9,
	0x51, 0x92, 0x47, 0x5d, 0xd8, 0xa9, 0xc1, 0x25, 0x99, 0xe3, 0x32, 0x15, 0x96, 0x86, 0xfe, 0xc2,
	0x96, 0x22, 0x8a, 0xd8, 0x02, 0xa8, 0x03, 0x9b, 0x35, 0x1a, 0x17, 0xb1, 0xa5, 0x87, 0xa3, 0xd5,
	0xc6, 0x05, 0xeb, 0x8d, 0x0b, 0x3e, 0x36, 0x2e, 0x78, 0xfd, 0x74, 0xb5, 0xbb, 0xde, 0xde, 0xa9,
	0xf1, 0x72, 0x36, 0xc5, 0xf2, 0x05, 0xa5, 0xa0, 0xa9, 0xba, 0xf7, 0x85, 0xfa, 0xaa, 0x3f, 0x32,
	0x9c, 0x7e, 0x05, 0x00, 0x00, 0xff, 0xff, 0x51, 0xce, 0x9e, 0x32, 0xe3, 0x01, 0x00, 0x00,
}

func (m *PaginationReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PaginationReq) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PaginationReq) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Sort) > 0 {
		for k := range m.Sort {
			v := m.Sort[k]
			baseI := i
			i = encodeVarintPagination(dAtA, i, uint64(v))
			i--
			dAtA[i] = 0x10
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintPagination(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintPagination(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.PageSize != 0 {
		i = encodeVarintPagination(dAtA, i, uint64(m.PageSize))
		i--
		dAtA[i] = 0x10
	}
	if m.Page != 0 {
		i = encodeVarintPagination(dAtA, i, uint64(m.Page))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintPagination(dAtA []byte, offset int, v uint64) int {
	offset -= sovPagination(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *PaginationReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Page != 0 {
		n += 1 + sovPagination(uint64(m.Page))
	}
	if m.PageSize != 0 {
		n += 1 + sovPagination(uint64(m.PageSize))
	}
	if len(m.Sort) > 0 {
		for k, v := range m.Sort {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovPagination(uint64(len(k))) + 1 + sovPagination(uint64(v))
			n += mapEntrySize + 1 + sovPagination(uint64(mapEntrySize))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovPagination(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPagination(x uint64) (n int) {
	return sovPagination(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *PaginationReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPagination
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PaginationReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PaginationReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Page", wireType)
			}
			m.Page = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPagination
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Page |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PageSize", wireType)
			}
			m.PageSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPagination
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PageSize |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sort", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPagination
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPagination
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPagination
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Sort == nil {
				m.Sort = make(map[string]SortOrder)
			}
			var mapkey string
			var mapvalue SortOrder
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowPagination
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowPagination
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthPagination
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthPagination
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowPagination
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapvalue |= SortOrder(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipPagination(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthPagination
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Sort[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPagination(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPagination
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPagination(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPagination
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPagination
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPagination
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPagination
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPagination
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPagination
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPagination        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPagination          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPagination = fmt.Errorf("proto: unexpected end of group")
)
